#
# /etc/zshrc is sourced in interactive shells.  It
# should contain commands to set up aliases, functions,
# options, key bindings, etc.

path=(~/bin ~/Library/dot/bin /usr/local/bin $configpath/git /sbin /usr/sbin $path)
[[ -r .zshrc_/local_before.zshrc ]] && . .zshrc_/local_before.zshrc

stty -ixon

# oh-my-zsh

export CASE_SENSITIVE="true"  # why would you not use this by default? nothing
                              # more annoying then hitting /us<tab> and having
                              # to choose between /usr/ and /Users
ZSH=$HOME/.oh-my-zsh
ZSH_THEME="afowler"
plugins=(macos fasd)
[[ -r .zshrc_/oh-my-zsh.sh ]] && . .zshrc_/oh-my-zsh.sh
#alias ts=trash

setopt NO_BEEP


configpath="$HOME/Library/dot"

# Set up aliases

alias igrep='grep -i'
alias mkdir='nocorrect mkdir' # no spelling correction on mkdir
alias rrm=\"/bin/rm\" # no spelling correction on mkdir

unsetopt correct_all # fuck correction it's the most annoying feature in the world

# Set prompts
if [ $SHLVL -gt 2 ]
then
 export PROMPT="($SHLVL) $PROMPT"
fi

# Some environment variables

path=(~/bin ~/Library/dot/bin /usr/local/bin $configpath/git /sbin /usr/sbin $path ~/homebrew/bin ~/homebrew/sbin /opt/homebrew/bin)
export LC_ALL="en_US.UTF-8"
export LANG="en_US.UTF-7"

if [[ $OSTYPE[0,6] == "darwin" ]]
then
    [[ -r .zshrc_/mac.sh ]] && . .zshrc_/mac.sh
else
    [[ -r /usr/share/autojump/autojump.sh ]] && . /usr/share/autojump/autojump.sh
fi

export TRASH="$HOME/.Trash"

bindkey -v             # vi key bindings
bindkey ' ' magic-space  # also do history expansino on space

alias back='cd $OLDPWD'

autoload -U compinit && compinit -u

if command -v nvim &> /dev/null
then
  export EDITOR='nvim'
  alias vimdiff="nvim -d"
else
  export EDITOR='vim'
fi

# vi style incremental search

bindkey -M vicmd '?' history-incremental-pattern-search-forward
bindkey -M vicmd '/' history-incremental-pattern-search-backward
bindkey -M viins '^K' history-incremental-pattern-search-backward
bindkey -M viins '^J' history-incremental-pattern-search-forward

# Beginning search with arrow keys
#bindkey -M vicmd "k" up-line-or-beginning-search
#bindkey -M vicmd "j" down-line-or-beginning-search

export KEYTIMEOUT=1

[[ -s $HOME/.tmuxinator/scripts/tmuxinator ]] && source $HOME/.tmuxinator/scripts/tmuxinator

for file in $configpath/etc/zshrc_/*
    . $file

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

[[ -r .zshrc_/local_after.zshrc ]] && . .zshrc_/local_after.zshrc
