#
# /etc/zshrc is sourced in interactive shells.  It
# should contain commands to set up aliases, functions,
# options, key bindings, etc.

configpath="$HOME/Library/dot"

path=(~/bin ~/Library/dot/bin /usr/local/bin $configpath/git /sbin /usr/sbin $path)
ZSHRC_PATH=~/.zshrc_
[[ -r $ZSHRC_PATH/local_before.zshrc ]] && . $ZSHRC_PATH/local_before.zshrc

stty -ixon

export CASE_SENSITIVE="true"  # why would you not use this by default? nothing
                              # more annoying then hitting /us<tab> and having
                              # to choose between /usr/ and /Users

setopt NO_BEEP

# Set up aliases

alias igrep='grep -i'
alias mkdir='nocorrect mkdir' # no spelling correction on mkdir
alias rrm=\"/bin/rm\" # no spelling correction on mkdir

unsetopt correct_all # fuck correction it's the most annoying feature in the world
setopt interactivecomments  # o/w mac thinks comments are commands
alias ls='ls --color=auto'

export PROMPT="%m :: %F{green}%~ %F{reset_color}» "

# Set prompts
#if [ $SHLVL -gt 2 ]
#then
 #export PROMPT="($SHLVL) $PROMPT"
#fi

# Some environment variables

path=(~/bin ~/Library/dot/bin /usr/local/bin $configpath/git /sbin /usr/sbin $path)
export LC_ALL="en_US.UTF-8"
export LANG=en_US.UTF8

if [[ $OSTYPE[0,6] == "darwin" ]]
then
    path=($path ~/homebrew/bin ~/homebrew/sbin /opt/homebrew/bin)
    [[ -r $zsh_config_path/mac.sh ]] && . $zsh_config_path/mac.sh
else
    [[ -r /usr/share/autojump/autojump.sh ]] && . /usr/share/autojump/autojump.sh

    # Beginning search with arrow keys
    bindkey "^[OA" up-line-or-beginning-search
    bindkey "^[OB" down-line-or-beginning-search
    bindkey -M vicmd "k" up-line-or-beginning-search
    bindkey -M vicmd "j" down-line-or-beginning-search
fi

source $HOME/.zshrc_/zsh-histdb/sqlite-history.zsh
autoload -Uz add-zsh-hook

export TRASH="$HOME/.Trash"

bindkey -v             # vi key bindings
bindkey ' ' magic-space  # also do history expansino on space

alias back='cd $OLDPWD'

autoload -U compinit && compinit -u

if command -v nvim &> /dev/null
then
  export EDITOR='nvim'
  alias vimdiff="nvim -d"
else
  export EDITOR='vim'
fi

# vi style incremental search

bindkey -M vicmd '?' history-incremental-pattern-search-forward
bindkey -M vicmd '/' history-incremental-pattern-search-backward
bindkey -M viins '^K' history-incremental-pattern-search-backward
bindkey -M viins '^J' history-incremental-pattern-search-forward

# Beginning search with arrow keys
#bindkey -M vicmd "k" up-line-or-beginning-search
#bindkey -M vicmd "j" down-line-or-beginning-search

export KEYTIMEOUT=1

PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

[[ -r $ZSHRC_PATH/local_after.zshrc ]] && . $ZSHRC_PATH/local_after.zshrc

export HISTFILE=$HOME/.zsh_history
export SAVEHIST=100000000
export HISTSIZE=100000000

setopt EXTENDED_HISTORY
setopt APPEND_HISTORY
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY

cle() {
  nvim `which $1`
}
